#!/bin/bash

dir="build"
sleepTime='0.1'
sleepTime2='0.01'

echo -n "building "
sleep $sleepTime2 ; echo -n "."
mkdir -p $dir
sleep $sleepTime2 ; echo -n "."
cd $dir && sleep $sleepTime2 ; echo -n "." ; sleep $sleepTime ; echo ""
cmake .. && echo done && sleep 1 && make && cd .. && cp $dir/IceEngine .
